ALTER TABLE ADHERANT DROP COLUMN Categorie;

ALTER TABLE ADHERANT ADD Id_Categorie INT NULL;

ALTER TABLE ADHERANT ADD CONSTRAINT fk_Id_Categorie FOREIGN KEY (Id_Categorie) REFERENCES CATEGORIE(Id);

ALTER TABLE ADHERANT ADD Email VARCHAR(200) NULL;

ALTER TABLE ADHERANT ADD DateNaissance Date NULL;